### ISSUE TITLE
Neynar middleware issue on nodeJS

### ISSUE THREAD

**Issue by m4nuC** [wevm/frog-archived#120]
### Describe the bug

When using NodeJS, starting the app give the following error:

```
TypeError: Response body object should not be disturbed or locked
    at extractBody (node:internal/deps/undici/undici:5676:17)
    at new Request (node:internal/deps/undici/undici:6673:48)
    at new Request (file:///app/node_modules/@hono/node-server/dist/index.mjs:17:5)
    at file:///app/src/index.tsx:1:1247
     at dispatch (file:///app/node_modules/hono/dist/compose.js:29:23)
    at file:///app/node_modules/hono/dist/compose.js:30:20
    at logger2 (file:///app/node_modules/hono/dist/middleware/logger/index.js:35:11)
    at dispatch (file:///app/node_modules/hono/dist/compose.js:29:23)
    at file:///app/node_modules/hono/dist/compose.js:30:20
    at file:///app/node_modules/frog/_lib/middlewares/neynar.js:33:15

```

**Comment by dalechyn** [comment]
Please provide a reproducible example 🙏

**Comment by tmm** [comment]
Closing until we get a minimal reproduction.
