### ISSUE TITLE
Error in example: npm init frog -- -t vercel

### ISSUE THREAD

**Issue by Tisi22** [wevm/frog-archived#247]
### Describe the bug

When I run npm run dev I am getting:

```
1:15:19 PM [vite] Internal server error: Unknown error: [object Response]
      at Object.errorHandler (file:///home/tisi/mintworld-minis/v2/frogfm/my-first-frog/node_modules/frog/_lib/cli/vite/dev.js:104:31)
      at responseViaResponseObject (file:///home/tisi/mintworld-minis/v2/frogfm/my-first-frog/node_modules/@hono/node-server/dist/index.mjs:299:38)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) (x12)
```

### Steps To Reproduce

npm init frog -- -t vercel
npm install
npm run dev

### Frog Version

latest

### TypeScript Version

^5.3.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by Serpentum** [comment]
Same problem

**Comment by ngmisl** [comment]
Yep same here using bun

**Comment by dalechyn** [comment]
Fixed in https://github.com/wevm/frog/commit/dd0d2972bd6343315c4ff1ad91426994a0786870.
