### ISSUE TITLE
"frog dev" command fails due to Bun integration issue

### ISSUE THREAD

**Issue by matthewmorek** [wevm/frog-archived#403]
### Describe the bug

When running the `frog dev` command, an error occurs related to the Bun integration with `hono/bun`. The error suggests that Bun is not defined, which prevents the development server from starting correctly, though this is incorrect because Bun is available in the system.

Looks like Frog is not reading Bun dependencies correctly, although the `bun serve` runs perfectly fine. **This affects local development environment only.**

Full error log:
```sh
$ frog dev
19:07:44 [vite] Error when evaluating SSR module frames-frog-api/src/index.tsx: failed to import "hono/bun"
|- ReferenceError: Bun is not defined
    at frames-frog-api/node_modules/hono/dist/adapter/bun/ssg.js:3:17
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async nodeImport (frames-frog-api/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53536:15)
    at async ssrImport (frames-frog-api/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53392:16)
    at async eval (/Users/mmorek/Projects/ponder/frames-frog-api/src/index.tsx:6:31)
    at async instantiateModule (frames-frog-api/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53451:5)

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

ReferenceError: Bun is not defined
    at frames-frog-api/node_modules/hono/dist/adapter/bun/ssg.js:3:17
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at async nodeImport (frames-frog-api/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53536:15)
    at async ssrImport (frames-frog-api/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53392:16)
    at async eval (/Users/mmorek/Projects/ponder/frames-frog-api/src/index.tsx:6:31)
    at async instantiateModule (frames-frog-api/node_modules/vite/dist/node/chunks/dep-CzJTQ5q7.js:53451:5)

Node.js v20.12.2
error: script "dev" exited with code 1
```

### Link to Minimal Reproducible Example

https://github.com/matthewmorek/frames-frog-api

### Steps To Reproduce

1. Install Bun
2. Install repo dependencies
3. Run `bun dev`

From scratch:
1. Create a new project using steps from the Bun guide in Frog.fm docs
2. Change import source for `serveStatic` from `frog/serve-static` to `hono/bun`
3. Run `bun dev`

### Frog Version

0.12.2

### TypeScript Version

5.5.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/frog/issues) for the bug I encountered.

**Comment by tmm** [comment]
```diff
- import { serveStatic } from 'hono/bun'
+ import { serveStatic } from 'frog/serve-static'
```

**Comment by matthewmorek** [comment]
If that's the case, the [Frog integration docs for Bun](https://frog.fm/platforms/bun#setup-devtools) need to be updated as they currently guide people to add `hono/bun` instead, causing the issue to begine with. See below:
![image](https://github.com/wevm/frog/assets/1137994/6d4a9690-a336-4e68-af6a-3648356aa91b)

**Comment by tmm** [comment]
Feel free to create a pull request!
